describe('Tugas 5', function (){
    it('Case Study 2', function (){
        cy.visit('https://demoqa.com/automation-practice-form/')
        cy.get('#stateCity-wrapper > :nth-child(2)',{force:false}).should('be.not.selected')
        cy.get('#stateCity-wrapper > :nth-child(3)',{force:false}).should('be.not.selected')
        cy.get('#firstName').type('Jaeger').should('have.value','Jaeger')
        cy.get('#lastName').type('Dorn').should('have.value','Dorn')
        cy.get('#userEmail').type('dorn@gmail.com').should('have.value','dorn@gmail.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)',{force:true}).click().should('be.visible')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').should('have.text','Male')
        cy.get('#userNumber').type('00011000').should('have.value','00011000')
        // cy.get('#dateOfBirthInput').invoke('val','30 Dec 2000').should('have.value','30 Dec 2000')
        cy.get('#dateOfBirthInput',{force:true}).click().type('{selectall}','{backspace}').type('16 Oct 1994').type('{enter}').should('have.value','16 Oct 1994')
        cy.get('.subjects-auto-complete__value-container').type('English{enter}')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').should('have.text','Sports')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').should('have.text','Reading')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').should('have.text','Music')
        cy.wait(800)
        cy.get('#uploadPicture').attachFile('5f4745c9d3533ae6680adf3d6dd0ef3a_t.jpg')
        cy.get('#currentAddress').type('Jakarta Timur').should('have.value','Jakarta Timur')
        cy.get('#city').find('input').should('be.disabled')
        cy.get('#state',{force:true}).type('Haryana{enter}')
        cy.wait(800)
        cy.get('#city',{force:true}).type('Karnal{enter}')
        cy.wait(800)
        cy.get('#submit').should('be.visible').click()
        cy.get('.modal-header').should('have.text','Thanks for submitting the form')
        cy.get('tbody > :nth-child(7) > :nth-child(2)').should('have.text','Sports, Reading, Music')
        cy.get('#closeLargeModal',).should('have.text','Close').click({force:true})
    })
})