describe('Pkh test 3', function (){
    it('tc-ubahFacil2', function(){
        cy.pkh()
        cy.get('input[id="input-email"]',{force:true}).type('e@dojobox.id').should('have.value','e@dojobox.id')
        cy.get('input[id="input-password"]',{force:true}).type('admin').should('have.value','admin')
        cy.get('#btn-login').should('be.visible').click({force:true})
        cy.get('#dataTable_filter > label > .form-control').type('wong ndablek').should('have.value','wong ndablek')
        cy.wait(800)
        cy.get('.btn-group > .btn').click()
        cy.get('[href="facilitator/edit/251"]').click()
        cy.get('.info-dasar > h5.text-dark').should('have.text','Informasi Dasar')
        cy.get('.info-dasar > :nth-child(2) > .text-dark').should('have.text','Nama Fasilitator')
        cy.get('input[id="user_fullname"]').click().type('{selectall}','{backspace}').type('wong ndablek',{force:true}).should('have.value','wong ndablek')
        cy.get('input[id="user_email"]').click().type('{selectall}','{backspace}').type('edanemen@gmail.com',{force:true}).should('have.value','edanemen@gmail.com')
        cy.get('#user_is_active',{force:true}).select('Aktif')
        cy.get('input[id="user_password"]').click().type('{selectall}','{backspace}').type('ndablek',{force:true}).should('have.value','ndablek')
        cy.get('#user_province_id').select('JAWA TIMUR').should('have.value','35')
        cy.get('#user_city_id').select('KOTA SURABAYA').should('have.value','3578')
        cy.get('#user_subdistrict_id').select('Sukolilo').should('have.value','357809')
        cy.get('textarea[id="user_address"]').click().type('{selectall}','{backspace}').type('omah edan',{force:true}).should('have.value','omah edan')
        // cy.get('#user_address').type('omah gede',{force:true}).should('have.value','omah gede')
        cy.get('#drop-zone').attachFile('209377413_2706495079652346_3575576564316998897_n.jpg')
        // cy.get('.py-2',{force:true}).click()
        cy.get('#user_area_province_id').select('JAWA TIMUR').should('have.value','35')
        cy.get('#user_area_city_id').select('KAB. MALANG').should('have.value','3507')
        cy.get('#user_area_subdistrict_id').select('Lawang').should('have.value','350725')   
        cy.get('button[id="edit"]').should('be.visible').click()
        cy.get('#modal-title').should('have.text','Success')
        cy.get('#modal-body').should('have.text','Perubahan fasilitator berhasil diproses')
        cy.get('#generalModal > .modal-dialog > .modal-content > .modal-footer > .btn').should('be.visible').click({force:true})
    })
})